version: '3.9'

volumes:
  pgdata:

services:

  db:
    image: postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
#      PGDATA: "/var/lib/postgresql/data/pgdata"
#    volumes:
#      - .:/docker-entrypoint-initdb.d
#      - pgdata:/var/lib/postgresql/data

#  app:
#    build: .
#    container_name: backend_app
#    ports:
#      - "5000:5000"
#    depends_on:
#      - db
#    environment:
#      SECRET_KEY: ${SECRET_KEY}
#    restart: on-failure
#    command: flask run -h 0.0.0.0



