version: '3.9'

networks:
  dev_network:

services:

  db:
    image: postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

#  app:
#    build: .
#    container_name: backend_app
#    ports:
#      - "5000:5000"
#    depends_on:
#      - db
#    environment:
#      PG_USER: ${DB_USER}
#      PG_PASSWORD: ${DB_PASSWORD}
#      PG_HOST: ${DB_HOST}
#      PG_PORT: ${DB_PORT}
#      PG_DB: ${DB_NAME}
#    command: sh -c "gunicorn app:app --bind 0.0.0.0:5000 --capture-output"